<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>非同期 on ベインのブログ</title>
    <link>https://vain0x.github.io/blog/tags/%E9%9D%9E%E5%90%8C%E6%9C%9F/</link>
    <description>Recent content in 非同期 on ベインのブログ</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>ja-jp</language>
    <managingEditor>vainzerox@gmail.com (ベイン)</managingEditor>
    <webMaster>vainzerox@gmail.com (ベイン)</webMaster>
    <lastBuildDate>Sat, 23 Dec 2017 00:00:00 +0000</lastBuildDate><atom:link href="https://vain0x.github.io/blog/tags/%E9%9D%9E%E5%90%8C%E6%9C%9F/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>async関数が例外を捕捉する挙動について</title>
      <link>https://vain0x.github.io/blog/2017-12-23/async-function-and-exception/</link>
      <pubDate>Sat, 23 Dec 2017 00:00:00 +0000</pubDate>
      <author>vainzerox@gmail.com (ベイン)</author>
      <guid>https://vain0x.github.io/blog/2017-12-23/async-function-and-exception/</guid>
      <description></description>
    </item>
    
  </channel>
</rss>
